### ISSUE TITLE
Support Through Steam

### ISSUE THREAD

**Issue by aminecraftplayerx** [voxeltycoon/issues#733] opened 2021-05-09 21:53 UTC
I've been trying to figure out some problems I have been having through the Steam forums. I've seen you state on there that you aren't bothering to read the Steam discussions and are rather requiring people to report problems here. You are on Steam early access, you need to support Steam early access through Steam.

**Comment by voxeltycoon** [comment] 2021-05-09 22:58
Duplicate of https://github.com/voxeltycoon/issues/issues/732.

**Closed by voxeltycoon** 2021-05-09 22:58 UTC
Labels: duplicate
