### ISSUE TITLE
Videos in tutorial are unavailable

### ISSUE THREAD

**Issue by AlexWayfer** [voxeltycoon/issues#873] opened 2021-07-07 19:28 UTC
**Describe the bug**

At each tutorial stage I see a box with "Play" button and gray background. I guess, there are supposed to be videos with preview/instructions.

**Steps to reproduce**

Start tutorial, loop at the top of window.

**Build version**

I can't start the game on Linux for the second time, after exit. I don't know why. Anyway, the latest available version at 2021-07-07, judging by the game news — 0.86.1.

**Platform**

Windows and Linux.

**Reproducibility**

2 / 2 on Win and 1 / 1 on Linux.

**Logs/saves**

Do you need some? Or can you confirm without them?

**Comment by andrewpey** [comment] 2021-11-12 16:28
Originally it was believed that it's caused by [this bug](https://issuetracker.unity3d.com/issues/windows-7-windowsvideomedia-error-0xc00d36b4-error-is-thrown-when-loading-a-video-with-the-videoplayer) in the Unity engine. But they stated they have fixed it in the 2020.3.7 version of the engine, and the 0.86 runs on the 2020.3.12. So, it might be a new bug.

Can I ask you to provide a log files from both Windows and Linux so we can look into them?

**Comment by andrewpey** [comment] 2022-09-14 17:00
No info was provided, closing.

**Closed by andrewpey** 2022-09-14 17:00 UTC
