### ISSUE TITLE
No compensation for replacing semaphores/signals during the pause

### ISSUE THREAD

**Issue by prostolyubo** [voxeltycoon/issues#681] opened 2021-05-02 13:32 UTC
**Describe the bug**
When the game is paused objects can be placed and destroyed for a full refund. However, if a signal is replaced by another type of a signal - the refund do not happen.

**Steps to reproduce**
1. Pause the game.
2. Build a short section of rails.
3. Place a pre-signal.
4. Note down your cash balance.
5. Destroy the pre-signal (full refund happens).
6. Place a signal in the same spot.
7. Check the balance. It should be greater than the noted down one.
8. Destroy the signal.
9. Place a pre-signal.
10. Place a signal in the same spot as the pre-signal (replace it).
11. Check the balance again. It is lower, than the noted one - you were not refunded for the pre-signal.

**Build version**
0.85.1

**Platform**
Windows 10

**Reproducibility**
100%

**Comment by polak-jan** [comment] 2021-05-02 13:46
This is a duplicate of #584. See comments on that report for more information.

**Closed by polak-jan** 2021-05-02 13:46 UTC
