### ISSUE TITLE
Different train blocks are considered the same if they are close enough.

### ISSUE THREAD

**Issue by rafaladamczyk** [voxeltycoon/issues#889] opened 2021-08-23 11:34 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/16541269/130439923-c9cf5a99-68a4-4d3e-8121-8c07f37781e0.png)

Take a look at the red train blocks. These are one-way blocks going in opposite directions but the game considers them to be the same, as evidenced by red signal.
The signal will turn green as soon as the train going the opposite direction leaves the red block.

**Steps to reproduce**
Not sure. Probably have two one-way blocks going in opposite directions very close to one another, but I haven't tested it.

**Build version**
0.86.1.steam

**Platform**
Win 10

**Reproducibility**
I only spotted it in this instance.

**Logs/saves**
Savegame attached:
[thdbbahrhsg.zip](https://github.com/voxeltycoon/issues/files/7031501/thdbbahrhsg.zip)

**Comment by Foxdrew** [comment] 2021-08-23 11:40
Its not bug, Very close to one another.

**Comment by Foxdrew** [comment] 2021-08-23 11:41
If you dont have "this logic" trains in this block will crash

**Comment by rafaladamczyk** [comment] 2021-08-23 17:26
If so then I think it's really unintuitive and it would be better if it was not possible for 2 trains going in on separate tracks to crash.

**Comment by andrewpey** [comment] 2021-08-23 21:46
As Foxdrew mentioned, this is not a bug, but we are aware that this might be confusing. This should be fixed with the introduction of the new tracks system: https://voxeltycoon.xyz/devlog/ea-faq/#i-have-hard-times-building-bridges-connecting-roads-etc

BTW, there's already a discussion for that: https://github.com/voxeltycoon/issues/discussions/591

**Closed by andrewpey** 2021-08-23 21:46 UTC
