### ISSUE TITLE
game crashes on exploring world

### ISSUE THREAD

**Issue by Wollknaeuel** [voxeltycoon/issues#888] opened 2021-08-21 15:33 UTC
**Describe the bug**
the game crashes on loading a new game, at the point exploring new world.

**Steps to reproduce**
just start a new game and while loading it crashen at the point of exploring new wolrd.

**Build version**
V0.86.1

**Platform**
Manjaro KDE updated to lates version.
Game ist buyed at steam store and even on lates version thats avaibele.

**Reproducibility**
How often an issue reproduces: every time

https://user-images.githubusercontent.com/89309980/130326993-524f7476-9f71-4fbe-8812-eefffada0cf6.mp4

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/issues/discussions/650) if applicable.

**Comment by andrewpey** [comment] 2021-08-21 18:50
Can we see the [logs](https://github.com/voxeltycoon/issues/discussions/650)?

**Comment by Wollknaeuel** [comment] 2021-08-21 21:39
the only thing i have is the screen record. where can i find the logs?

Am Sa., 21. Aug. 2021 um 20:50 Uhr schrieb Andrey Peysakhovich <
***@***.***>:

**Comment by Wollknaeuel** [comment] 2021-08-21 21:58
found it.

Am Sa., 21. Aug. 2021 um 23:39 Uhr schrieb Wollknäuel <
***@***.***>:

**Comment by andrewpey** [comment] 2021-11-12 16:32
Any news on the logs?

**Comment by Wollknaeuel** [comment] 2021-11-12 16:35
i send the log on my last mail. but i switched from my pc to my laptop and
play on win 10.
i attached the log file on this mail.
 mfg hahnkow


Am Fr., 12. Nov. 2021 um 17:32 Uhr schrieb Andrey Peysakhovich <
***@***.***>:

**Comment by andrewpey** [comment] 2021-11-12 16:47
Unfortunately, it doesn't seem to be attached via email responses. Could you try to attach it via the web interface, please?

**Comment by Wollknaeuel** [comment] 2021-11-12 16:49
[Player.log](https://github.com/voxeltycoon/issues/files/7529113/Player.log)
i hope it goes this time.

**Comment by andrewpey** [comment] 2021-11-12 17:04
Yeah, it worked now, thanks.

**Comment by andrewpey** [comment] 2021-11-12 17:30
Could you please try to install the [mono](https://archlinux.org/packages/extra/x86_64/mono/) package and see if this helps?

**Comment by Wollknaeuel** [comment] 2021-11-12 17:37
it is installed as depandescy from lutris.
i have installed as dependescy from lutris, steam:
- mono
- mono addins
- gendarme (mono-tools)
- mono msbuild
- mono- msbuild-sdkresolver

its installed at setting up my manjaro for gaming, long before i buyed
voxel tycoon.
its all installed from the repo extra from manjaro, its not from the aur.

mfg hahnkow

Am Fr., 12. Nov. 2021 um 18:30 Uhr schrieb Andrey Peysakhovich <
***@***.***>:

**Comment by andrewpey** [comment] 2021-11-12 17:54
I see, thanks for the info. Also, can I ask you to try starting a new game with no mods enabled?

**Comment by Wollknaeuel** [comment] 2021-11-12 18:06
the video was without mods enabled. it was the first i thought, that mods
causing the crash.
i even uninstalled all the mods, but the game is still crashing. thats why
i play it at win 10 on the laptop.
could it be that unity has a problem with the grafik software for amd
radoen, that is in the linux kernel?
a friend of mine suggested it, but i didnt found anything about it on the
internet/amd page or at the kernel log page.
the thing is voxel tycoon ist the only game made with unity i have. all
other games are for win 10 only, they use lutris or steam proton to run on
manjaro. voxel is the only one who dont uses those compatibility layers.
 for me is it not important that it crashes on linux, i have my acer
predator g15 laptop with win 10.

i thought that it gives an easy solution for the crashes, thats was the
reason i opened the ticket.

mfg hahnkow

Am Fr., 12. Nov. 2021 um 18:55 Uhr schrieb Andrey Peysakhovich <
***@***.***>:

**Comment by andrewpey** [comment] 2021-11-12 18:25
Yeah, that could be of course caused by a lot of reasons, and it's really hard to debug since it occurs not in our code but deep inside in Unity engine. Luckily you have another machine to play.

I think we'll close this issue for now since it is not clear where we can move from here. Thanks for raising it anyway.

**Closed by andrewpey** 2021-11-12 18:25 UTC

**Comment by Wollknaeuel** [comment] 2021-11-12 18:28
ok, i understand the reason and i wish you a good weekend.
thanks for the try to help.

mfg hahnkow

Am Fr., 12. Nov. 2021 um 19:25 Uhr schrieb Andrey Peysakhovich <
***@***.***>:
