### ISSUE TITLE
MacOS and Running out of Application Memory

### ISSUE THREAD

**Issue by DonMarco** [voxeltycoon/issues#984] opened 2022-09-18 14:56 UTC
**Describe the bug**
After running a game for 5-10min, MacOS shows an error message, regarding the application using up all application memory and wanting me to shut down certain programs.
This problem did not occur a while ago, but for the last past weeks (unsure if it is regarding a MacOS update or a Voxel Tycoon update I am unable to play for longer than 10-15min.
<img width="587" alt="Screenshot 2022-09-18 at 16 51 43" src="https://user-images.githubusercontent.com/4727267/190913372-777443f2-fe52-4ceb-b5fb-c6bb585cb887.png">
<img width="633" alt="Screenshot 2022-09-18 at 16 43 55" src="https://user-images.githubusercontent.com/4727267/190913354-1090eb3d-4e41-4b10-9727-9765288755f4.png">
 

**Steps to reproduce**
Start Voxel Tycoon with a M1 MacOS computer (laptop).
Start a game. Monitor application memory, which runs at least up to 100gb.

**Build version**
0.87.2.3 (and the version before)

**Platform**
MacOS 12.5.1 with M1

**Reproducibility**
everytime

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/issues/discussions/650) if applicable.

**Comment by andrewpey** [comment] 2022-09-18 15:59
Duplicate of #924, #918.

**Closed by andrewpey** 2022-09-18 15:59 UTC
