### ISSUE TITLE
Diagonal parallel tracks (set too close?) break one way signal systems 

### ISSUE THREAD

**Issue by thomaslecointre** [voxeltycoon/issues#676] opened 2021-05-01 18:10 UTC
Here are two trains trying to get past eachother. The bottom train should be able to go ahead on the right hand track as no train is in front but the signal is set to red incorrectly:
![image](https://user-images.githubusercontent.com/16100057/116791193-ee152680-aab8-11eb-9c7b-0cb7b875620b.png)

Temporay solution is to space out the diagonal section by at least one tile:
![image](https://user-images.githubusercontent.com/16100057/116791251-44826500-aab9-11eb-9dd0-a9f47ddb81ce.png)

Image with after trains are past eachother:
![image](https://user-images.githubusercontent.com/16100057/116791270-65e35100-aab9-11eb-9706-74db79803eff.png)

**Comment by polak-jan** [comment] 2021-05-01 18:19
Duplicate of #591

**Closed by polak-jan** 2021-05-01 18:19 UTC
